### ISSUE TITLE
Install location

### ISSUE THREAD

**Issue by numpty9989** [metallicgloss/WHMCS-Discord-Notifications#1]
I am trying to get this installed I have put it in includes/hooks/WHMCS-Discord-Notifications.php
I have filled all the info into the PHP file with the admin area webhook URL company name but I am wondering why nothing happens when we get a new order/ticket

can you help me please

**Comment by metallicgloss** [comment]
Hello.

Have you made sure to edit the variables in every location they appear rather than just at the top in the commented or section?

It would appear to be a configuration problem as the script is currently being used by a lot of people and myself included and I haven't come across an error with it recently.

**Comment by numpty9989** [comment]
I have added the correct variables in every location I can include a screenshot with the personal ingot blurred obs
https://cl.ly/002n1u2G3S2w
https://cl.ly/2a3y42021F1M
https://cl.ly/2G2r1r0P3r0U
https://cl.ly/1T45111M2j2F
https://cl.ly/0b0h3F3I422w
https://cl.ly/0K312X333J0D
i  have not added the client id but i have tried it with it too and still nothing
i have also made my admin= URL https:///mywebsirte/adminpage/ obviously an example but  i included the / at the end

**Comment by metallicgloss** [comment]
Thank you for getting back to me.

Can you confirm that the web hook generated is pointing to the correct channel? It is rather hard to assist with no logs or errors, just the fact it isn't working.

If you've double checked that it is going to where you need it to I would recommend re-downloading it, configuring it one section at a time to see if there is a point or section where the configuration was botched.

Let me know how it goes!

**Comment by numpty9989** [comment]
it is set tp post in the General chat

https://cl.ly/3F1D3A123D0u
https://cl.ly/1R2g272n310b

**Comment by metallicgloss** [comment]
Hello.

All I can recommend is attempt to reinstall the script, configure it slowly as you go. Without an error there isn't much I can offer. Sorry!

**Comment by numpty9989** [comment]
where would i find any error log if it creates them i have tested with a ticket to my test account but it didn't post in the discord

**Comment by metallicgloss** [comment]
You would find them within WHMCS's logs on the admin panel. Let me know if there is any there relating to this script.

**Comment by numpty9989** [comment]
Hooks Debug: Hook Defined for Point: AfterRegistrarRenewalFailed - Priority: 1 - Function Name: (anonymous function)
--

**Comment by numpty9989** [comment]
https://cl.ly/0m2L1S152a3F does that help  ???

**Comment by numpty9989** [comment]
https://cl.ly/1Z3j1W07013L

**Comment by numpty9989** [comment]
that shows it loaded the hook

**Comment by metallicgloss** [comment]
It doesn't look like anything is really going wrong, try reconfiguring the script slowly to see if it stops working at any point.

To my knowledge it currently works and is live on my system so the chances are a configuration issue has occurred or some syntax has been removed where it shouldn't.

If you need any further assistance please respond back with a formatted message on steps you have already taken to attempt to resolve the problem, errors relating specifically to the hook.

**Comment by numpty9989** [comment]
ok i will do one part at a time and see and post back

**Comment by metallicgloss** [comment]
Okay. I just removed a couple of your previous messages as they had errors relating to other scripts and did not assist in this matter at all.

**Comment by numpty9989** [comment]
it works i has removed a " it broke it you can close this now was my stupid mistake thanks for the help

**Comment by metallicgloss** [comment]
Hello.

No problem at all, glad it is all working well for you now!
