### ISSUE TITLE
Hebrew Not Working

### ISSUE THREAD

**Issue by joni7878** [metallicgloss/WHMCS-Discord-Notifications#12]
Hi I find a bug that lang Hebrew not working 
![image_2022-10-02_042415781](https://user-images.githubusercontent.com/83814664/193434007-fc41e9de-e4d4-43e3-bbfe-a0afde85a2a6.png)

**Comment by hadikhanian** [comment]
fixed
Line 584 (simpleFix Function):
` $value = iconv(mb_detect_encoding($value, mb_detect_order(), true), 'UTF-8', $value);`

**Comment by metallicgloss** [comment]
> fixed Line 584 (simpleFix Function): ` $value = iconv(mb_detect_encoding($value, mb_detect_order(), true), 'UTF-8', $value);`

Thanks for the contribution - I'll get it added in.
