### ISSUE TITLE
Something stopped working.

### ISSUE THREAD

**Issue by Kriiiiiiiz** [metallicgloss/WHMCS-Discord-Notifications#16]
At first I want to thank you for this awesome free and open source project, I've been using it for near two years with any issue, but I've just noticed that for some reason at 10th January 2023 it stopped working without any change or modification in its config. Could this have something to do with latest WHMCS update ? Did it stopped working for any one else ?

Many thanks !

**Comment by metallicgloss** [comment]
Hi!

I'm very glad to hear that you've been able to make use of it! It sounds very similar to another report #14 that also had the same problem on that date - it was caused by Discord cycling/removing their webhook. Could you give that a check?

**Comment by Kriiiiiiiz** [comment]
I did created a new webhook and still no notifications :(

**Comment by metallicgloss** [comment]
Did you manage to get this resolved? There haven't been any other large increase in reports of something breaking, and it continues to work with the latest version of WHMCS.

**Comment by Kriiiiiiiz** [comment]
Once again trying to set up the hook with the new php file, updated 7 months ago and still can manga to make it work again... :(
