### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by lferezy4** [metallicgloss/WHMCS-Discord-Notifications#3]
im trying to use this and i configured it correctly i think, I added the discord webhook at the top and chose my company name and put the admin URL location. is there anything else i need to do to make it work?

**Comment by metallicgloss** [comment]
Hello.

Please read the comments at the top of the file, it will explain everything you have to configure. The script is currently working. If your install isn't, try re-downloading the script and re-configuring it to ensure you haven't missed something or set something incorrectly.
