### ISSUE TITLE
To-do notification

### ISSUE THREAD

**Issue by anondev-sudo** [metallicgloss/WHMCS-Discord-Notifications#8]
Add notification when something has been added to your to-do list. Useful when you use auto release module for product and want to be notified when you should setup the service.

**Comment by metallicgloss** [comment]
Unfortunately, it doesn't look like there are any hooks available in WHMCS to allow for this script to tap into the functionality that you've requested. You can see the full list of hooks available at https://developers.whmcs.com/hooks/hook-index/ and it doesn't appear to offer anything related to the To-Do list at the current point in time.

Depending on your use case, I'd recommend looking at https://developers.whmcs.com/hooks-reference/module/#aftermodulecreate to add a custom notification to the script depending on your provisioning module requirements.

**Comment by anondev-sudo** [comment]
Ok, but I use auto release module. I have an idea, could you create module Discord auto release, that on all those actions (create, suspend, unsuspend, terminate, renew), detailed notification would be sent to Discord webhook?

**Comment by metallicgloss** [comment]
I can see a separate dedicated provisioning module purely focused on sending Discord notifications being potentially useful for some. Should I have time in the future, I'll certainly consider it.

**Comment by anondev-sudo** [comment]
Ok, thanks. If you consider it, let me know.

It will be really useful also for other users
